# Restaurant Data Cleaning & Preparation

In [87]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [127]:
df = pd.read_csv('zomato.csv')
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [12]:
df['listed_in(type)'].unique()

array(['Buffet', 'Cafes', 'Delivery', 'Desserts', 'Dine-out',
       'Drinks & nightlife', 'Pubs and bars'], dtype=object)

In [128]:
len(df)

51717

In [14]:
(df['menu_item'] == '[]').sum()

np.int64(39617)

In [129]:
(df["reviews_list"] == "[]").sum()

np.int64(7595)

## Understanding and cleaning  Data

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [131]:
df.describe()

              votes
count  51717.000000
mean     283.697527
std      803.838853
min        0.000000
25%        7.000000
50%       41.000000
75%      198.000000
max    16832.000000

In [91]:
df.isnull().sum()

url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

#### Checking for Empty values or empty lists

In [132]:
empty_list = pd.DataFrame({
    '[] count':(df == '[]').sum(),
    'percentage':((df == '[]').sum()/len(df)).round(2)
})
print(empty_list)

                             [] count  percentage
url                                 0        0.00
address                             0        0.00
name                                0        0.00
online_order                        0        0.00
book_table                          0        0.00
rate                                0        0.00
votes                               0        0.00
phone                               0        0.00
location                            0        0.00
rest_type                           0        0.00
dish_liked                          0        0.00
cuisines                            0        0.00
approx_cost(for two people)         0        0.00
reviews_list                     7595        0.15
menu_item                       39617        0.77
listed_in(type)                     0        0.00
listed_in(city)                     0        0.00

#### Dropping Unusefull columns or columns with many Empty lists

In [ ]:
df = df.drop(columns=['url','phone','menu_item'])
df.head()

In [134]:
df = df.dropna(subset = ['rest_type', 'location', 'approx_cost(for two people)', 'cuisines'])

In [135]:
df.isnull().sum()

address                            0
name                               0
online_order                       0
book_table                         0
rate                            7615
votes                              0
location                           0
rest_type                          0
dish_liked                     27713
cuisines                           0
approx_cost(for two people)        0
reviews_list                       0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

#### Handling Duplicate

In [136]:
df[df.duplicated()]

,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,listed_in(type),listed_in(city)
596,"572, 30th Main, 3rd Stage, Banashankari, Banga...",My Tea House,Yes,Yes,NEW,0,Banashankari,Casual Dining,NaN,"Continental, Asian, North Indian, Tea",500,"[('Rated 4.0', ""RATED\n So apparently I visit...",Dine-out,Banashankari
7599,"17, Thubarahalli Village, Hobli, Varthur Main ...",Nawab Di Biryani,Yes,No,NEW,0,Whitefield,"Takeaway, Delivery",NaN,"Biryani, Mughlai",400,"[('Rated 4.0', 'RATED\n Ordered paneer tikka ...",Delivery,Brookefield
9464,"744, 13th Main, 7th Cross, BTM 2nd Stage, BTM,...",Vyanjan,Yes,No,3.9/5,201,BTM,Quick Bites,"Poha, Jalebi, Paratha, Bhindi Masala, Kachori,...","North Indian, Street Food",300,"[('Rated 3.0', ""RATED\n Nice place, it's for ...",Delivery,BTM
9466,"607, First Floor, 80 Feet Road, 6th Block, Kor...",Carrots,Yes,Yes,4.1/5,600,Koramangala 6th Block,Casual Dining,"Pizza, Pasta, Salads, Masala Chai, Soya Butter...","Italian, North Indian, Healthy Food, Desserts","1,100","[('Rated 5.0', ""RATED\n It's the first vegan ...",Delivery,BTM
9467,"Building 58, New 3, A Main Road Marenahalli, J...",Eatsomnia,Yes,No,NEW,0,JP Nagar,Delivery,NaN,"North Indian, South Indian, Chinese, Continental",500,"[('Rated 1.0', ""RATED\n The worst food I ate ...",Delivery,BTM
9468,"6th Cross Road, Koramangala 6th Block, Bangalore",Rolls & Co,Yes,No,3.9/5,213,Koramangala 6th Block,Quick Bites,"Rolls, Chicken Wings, Shawarma, Chicken Tikka ...","Burger, Beverages, Rolls",400,"[('Rated 2.0', 'RATED\n Order : Peri Peri Fri...",Delivery,BTM
9469,"10, Opposite Forum Mall, Taverekere, Suddagunt...",Fogg,No,Yes,NEW,0,BTM,Quick Bites,NaN,"Fast Food, Chinese",200,"[('Rated 5.0', 'RATED\n Seafood soup - A Thai...",Delivery,BTM
9470,"Koramangala 1st Block, Bangalore",The Paratha Stories,Yes,No,3.3/5,36,Koramangala 1st Block,Delivery,NaN,North Indian,400,"[('Rated 3.0', 'RATED\n There is enough scope...",Delivery,BTM
9471,"29, 7th Cross Road, Bhavani Nagar, Suddagunte ...",Mycakeshop,Yes,No,NaN,0,BTM,Bakery,NaN,"Bakery, Desserts",300,"[('Rated 5.0', 'RATED\n I loved cake nice tru...",Delivery,BTM
9549,"51, 5th Main, 60 Feet Road, BNG Homestay Build...",Bisimillah Biriyani,No,No,3.5/5,11,BTM,Quick Bites,NaN,"Biryani, Fast Food",300,"[('Rated 4.0', 'RATED\n Very delicious food @...",Delivery,BTM
9638,"51, 5th Main, 60 Feet Road, BNG Homestay Build...",Bisimillah Biriyani's & Kebab's,No,No,3.3/5,6,BTM,Quick Bites,NaN,"Biryani, Fast Food",300,[],Delivery,BTM
12286,"The Millenia, The Market Place Food Court, Lev...",The Wok Shop,Yes,No,3.4/5,7,Ulsoor,Quick Bites,NaN,"Asian, Chinese, Momos, Fast Food, Indonesian, ...",500,"[('Rated 4.0', 'RATED\n Recently tried the Wo...",Delivery,Church Street
12287,"Q Court, 3rd Floor, Garuda Mall, Magarth Road,...",China South,Yes,No,NaN,0,Brigade Road,Casual Dining,NaN,"Chinese, Tibetan",600,"[('Rated 4.0', 'RATED\n Been at this place tw...",Delivery,Church Street
12288,"24/48, M Road Benson Town Frazer Town, Bangalore",Chination,No,No,NaN,0,Frazer Town,Delivery,NaN,Chinese,600,[],Delivery,Church Street
12289,"Garuda Mall, 3rd Floor, 15 Magrath Road, Craig...",Desi Streat,Yes,No,NaN,0,Brigade Road,Food Court,NaN,"South Indian, Street Food",400,"[('Rated 1.0', ""RATED\n Try asking for combo....",Delivery,Church Street
12290,"KH Marigowda Road, Near Hopcoms Complex, Shant...",Durga Sagar,Yes,No,3.3/5,8,Shanti Nagar,Quick Bites,NaN,South Indian,150,"[('Rated 4.0', 'RATED\n Ordered Anna sambar.....",Delivery,Church Street
12291,"34/2, Meaner Avenue Tank Road, Near Ulsoor Lak...",Happy Fillings,Yes,No,3.4/5,8,Ulsoor,Quick Bites,NaN,Chinese,300,"[('Rated 5.0', 'RATED\n A Good take away Chin...",Delivery,Church Street
12292,"25, Gover Road, Cox Town, Frazer Town, Bangalore",Marathi Biriyani House,Yes,No,3.3/5,6,Frazer Town,Quick Bites,NaN,"South Indian, Biryani",300,"[('Rated 4.0', 'RATED\n Happened to just come...",Delivery,Church Street
12293,"35, Ground Floor, Brigade Road, Shanthala Naga...",Meenu Oota Da Maane,Yes,No,3.2/5,23,Brigade Road,Casual Dining,NaN,"Seafood, Mangalorean, Chinese",700,"[('Rated 4.0', 'RATED\n One of the yummy food...",Delivery,Church Street
12294,"19, Saunder Road, Opposite Seventh Day Hospita...",Kareem's,Yes,No,3.6/5,32,Frazer Town,Quick Bites,NaN,"North Indian, Mughlai",700,"[('Rated 4.0', 'RATED\n Seen this restaurant ...",Delivery,Church Street
12295,"39, Coles Road, Cleveland Town, Pulikeshi Naga...",Robin Brown Ice Cream,Yes,No,NaN,0,Frazer Town,Dessert Parlor,NaN,Desserts,250,[],Delivery,Church Street
12296,"307, Thimmaiah Rd, Govinda Chetty Colony, Shiv...",Aubree,Yes,No,NaN,0,Shivajinagar,"Cafe, Bakery",NaN,"Cafe, Bakery",400,"[('Rated 5.0', ""RATED\n Aubree has become a v...",Delivery,Church Street
12303,"1, High Street, Cooke Town, Frazer Town, Banga...",Mudaliar's Kitchen,Yes,No,NaN,0,Frazer Town,Delivery,NaN,South Indian,500,[],Delivery,Church Street
12304,"11, 1st cross Road, Williams Town, Benson Town...",Kenz Karam,Yes,No,3.5/5,10,Frazer Town,"Takeaway, Delivery",NaN,"Desserts, Beverages",300,"[('Rated 5.0', 'RATED\n Brilliant Medoken. Ev...",Delivery,Church Street
12306,"Brigade Gateway, 26/1 DR. Rajkumar Road, Malle...",House Of Candy,Yes,No,NaN,0,Malleshwaram,Confectionery,NaN,Desserts,200,[],Delivery,Church Street
12314,"19/1, Queen's Road Cross, Munniswamy Road, Nea...",Ta'aam,Yes,No,4.1/5,402,Cunningham Road,Casual Dining,"Laham Mandi, Mutton Chops, Biryani, Mutton Sou...","North Indian, Mughlai, Arabian, Chinese",750,"[('Rated 4.0', ""RATED\n For all gluttons out ...",Delivery,Church Street
12322,"Alpine Annexed Apartment, Near ICICI Bank, Sha...",Promac Foods,Yes,No,NEW,0,Shanti Nagar,"Takeaway, Delivery",NaN,"North Indian, South Indian",250,[],Delivery,Church Street
12347,"Plot 62, Nanjappa Layout, Adugodi Main Road, A...",Ascharya Hotel,Yes,No,3.4/5,11,Koramangala 5th Block,Quick Bites,NaN,"Mangalorean, South Indian",300,"[('Rated 3.0', 'RATED\n I would say that thei...",Delivery,Church Street
12350,"16/3, Phoenix Arcade, Ground Floor, Shanthala ...",99 Pancakes,Yes,No,4.1/5,41,Church Street,Dessert Parlor,Nutella Pancakes,"Desserts, Ice Cream",150,"[('Rated 4.0', 'RATED\n Got the Nutella panca...",Delivery,Church Street
13442,"Opposite Velankani Gate number 2, Doddathoguru...",Lassi Adda,Yes,No,4.0/5,65,Electronic City,Beverage Shop,"Sweet Lassi, Corn Sandwich","Beverages, Sandwich, Fast Food",200,"[('Rated 4.0', 'RATED\n My favourite go to pl...",Delivery,Electronic City
13467,"65, TS Arcade, Next To Michelin Tyre Centre, C...",Sitaar,Yes,Yes,3.8/5,88,Electronic City,Casual Dining,NaN,"North Indian, Chinese",800,"[('Rated 5.0', ""RATED\n Really good food and ...",Delivery,Electronic City
17655,"Opposite Sri Subramanya Swamy Temple, Next to ...",New Taj,Yes,No,3.3/5,110,Ulsoor,Quick Bites,NaN,"North Indian, Chinese",300,"[('Rated 2.0', ""RATED\n It's my nature to try...",Delivery,Indiranagar
18715,"295/296, Ground Floor, 100 Feet Road, Indirana...",The Twisted Desi,Yes,Yes,NEW,0,Indiranagar,Casual Dining,NaN,"Continental, Italian, North Indian, Chinese","1,000",[],Dine-out,Indiranagar
20236,"746, 7th cross, 13th Main, BTM, Bangalore",Funky Punjab,Yes,No,3.8/5,125,BTM,Quick Bites,"Roti, Dal Makhani, Lassi, Panneer Butter Masal...","North Indian, Chinese",400,"[('Rated 3.0', ""RATED\n Wasn't as great as we...",Delivery,Jayanagar
20836,"36, Jaya Bheema Nagar, Layout 1, BTM, Bangalore",La Passion Cafe,Yes,No,NaN,0,BTM,Cafe,NaN,Cafe,500,[],Delivery,Jayanagar
20851,"3,11th Cross, Maruthi Nagar, 1st Stage, BTM, B...",Royal's Biryani,Yes,No,NaN,0,BTM,Quick Bites,NaN,Biryani,300,"[('Rated 4.0', 'RATED\n An amazing biryani pl...",Delivery,Jayanagar
20852,"14, Tank Shore Road, Kuvempu Nagar, Stage 2, B...",Tandoor Nation,Yes,No,3.0/5,39,BTM,Quick Bites,NaN,"North Indian, Chinese",400,"[('Rated 3.0', 'RATED\n Calm, cozy and open s...",Delivery,Jayanagar
20853,"242, 7th Main, Mico Layout, BTM, Bangalore",Indian Kitchen Eateries-IKE,Yes,No,3.4/5,8,BTM,Quick Bites,NaN,Fast Food,150,"[('Rated 5.0', 'RATED\n One of the best snack...",Delivery,Jayanagar
26434,"10, Babasabarapalya, Near Panchamukhi Ganesha ...",The Bridge Walk Cafe,No,No,3.8 /5,74,Kengeri,Cafe,NaN,"Cafe, Continental",500,"[('Rated 3.0', 'RATED\n This cafe opened up f...",Dine-out,Kammanahalli
28139,"1086/A, Twin Tulips, 18th Cross, 14th Main Roa...",Wedding Biryani,No,No,NEW,0,HSR,Quick Bites,NaN,"Biryani, Kebab",600,[],Delivery,Koramangala 4th Block
37692,"Ashraya Hotel, 149, Infantry Road, Bangalore",The Oriental Spice - Ashraya Hotel,Yes,No,3.9 /5,158,Infantry Road,Casual Dining,"Noodles, Lunch Buffet, Fish, Manchurian, Salad...","Chinese, Thai, Indonesian","1,300","[('Rated 4.0', 'RATED\n Had been there for a ...",Buffet,Lavelle Road
38109,"99, 3rd Main Road, Hanumanthnagar, Banashankar...",Sai Super Sandwich,Yes,No,NEW,0,Banashankari,Quick Bites,NaN,"Sandwich, Beverages",200,[],Delivery,Lavelle Road
38585,"Level 2, The Collection, UB City, Vithal Mally...",Rasovara,Yes,Yes,4.3 /5,772,Lavelle Road,Casual Dining,"Thali, Aamras, Malpua, Dal Bati, Lassi, Plain ...","Rajasthani, North Indian","1,400","[('Rated 4.0', 'RATED\n The problem here is a...",Dine-out,Lavelle Road
41404,"168/4, Ward 57, Abbaiah Reddy, Layout Main Roa...",Andhra Express,Yes,No,3.7 /5,19,CV Raman Nagar,"Takeaway, Delivery",NaN,"Andhra, Biryani, North Indian, Beverages",300,"[('Rated 5.0', 'RATED\n Amazing take away / h...",Delivery,Marathahalli
42312,"12/1, Swami Vivekananda Road, Jayaraj Nagar, S...",Shahi Family Restaurant,Yes,No,3.2 /5,88,Ulsoor,Quick Bites,NaN,"North Indian, Chinese, South Indian",350,"[('Rated 3.0', 'RATED\n Tried chicken biriyan...",Delivery,MG Road
42343,"Money Chambers Double Road, Shanti Nagar, Bang...",Red Onion,Yes,Yes,4.2 /5,570,Shanti Nagar,Casual Dining,"Fish, Dumplings, Biryani, Paneer Tikka Masala,...","Chinese, North Indian, Biryani, Kebab","1,200","[('Rated 5.0', 'RATED\n Was wandering around ...",Delivery,MG Road
43354,"36, Vittal Mallya Road, Lavelle Road, Bangalore",Bootlegger,No,No,4.1 /5,1545,Lavelle Road,Pub,"Beer, Cocktails, Beef Steak, Beef Chilli, Nach...","Continental, Steak","1,200","[('Rated 2.0', 'RATED\n Bootlegger is undoubt...",Dine-out,MG Road
43369,"Chancery Pavilion, 135, Residency Road, Bangalore",Ithaca - The Chancery Pavilion,No,Yes,3.9 /5,312,Residency Road,Fine Dining,"Salads, Sunday Brunch, Cocktails, Watermelon J...","North Indian, Italian, European, Continental","2,000","[('Rated 3.0', 'RATED\n The food was good\nTh...",Dine-out,MG Road
50904,"17, Thubarahalli Village, Hobli, Varthur Main ...",Nawab Di Biryani,Yes,No,NEW,0,Whitefield,"Takeaway, Delivery",NaN,"Biryani, Mughlai",400,"[('Rated 3.0', 'RATED\n Biriyani had ordered ...",Delivery,Whitefield

In [137]:
df = df.drop_duplicates()

#### Simplifying and cleaning the columns

In [138]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', 'NEW', '2.9/5', '3.5/5', nan, '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '-', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [139]:
(df['rate'].isin(['NEW', '-'])).sum()

np.int64(2261)

In [141]:
df['rate'].value_counts()[['NEW', '-']]

rate
NEW    2196
-        65
Name: count, dtype: int64

In [142]:
df['rate'] = df['rate'].replace(['NEW', '-'], np.nan)

In [143]:
df['rate'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '3.6/5', '4.6/5', '4.0/5', '4.2/5',
       '3.9/5', '3.1/5', '3.0/5', '3.2/5', '3.3/5', '2.8/5', '4.4/5',
       '4.3/5', nan, '2.9/5', '3.5/5', '2.6/5', '3.8 /5', '3.4/5',
       '4.5/5', '2.5/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5',
       '3.4 /5', '3.6 /5', '4.8/5', '3.9 /5', '4.2 /5', '4.0 /5',
       '4.1 /5', '3.7 /5', '3.1 /5', '2.9 /5', '3.3 /5', '2.8 /5',
       '3.5 /5', '2.7 /5', '2.5 /5', '3.2 /5', '2.6 /5', '4.5 /5',
       '4.3 /5', '4.4 /5', '4.9/5', '2.1/5', '2.0/5', '1.8/5', '4.6 /5',
       '4.9 /5', '3.0 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5',
       '2.1 /5', '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [144]:
df['rate'] = df['rate'].str.strip()
df['rate'] = df['rate'].str.replace('/5','', regex=False)
df['rate'] = pd.to_numeric(df['rate'], errors = 'coerce')
#"coerce means If you cannot convert a value to a number, don't throw an error. Instead, replace it with NaN."
df['rate']

0        4.1
1        4.1
2        3.8
3        3.7
4        3.8
        ...
51712    3.6
51713    NaN
51714    NaN
51715    4.3
51716    3.4
Name: rate, Length: 51099, dtype: float64

In [145]:
df['approx_cost(for two people)'] = (
    df['approx_cost(for two people)']
    .str.replace(',', '', regex=False)
)
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors = 'coerce' )

In [146]:
cols = ['address',
        'name',
        'location',
        'rest_type',
        'dish_liked',
        'cuisines',
        'reviews_list',
        'listed_in(type)',
        'listed_in(city)']
df[cols] = df[cols].apply(lambda col: col.str.strip())

In [147]:
df['rest_type'] = df['rest_type'].str.replace(
    'Irani Cafee',
    'Irani Cafe',
    regex=False
)

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51099 entries, 0 to 51716
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   address                      51099 non-null  object
 1   name                         51099 non-null  object
 2   online_order                 51099 non-null  object
 3   book_table                   51099 non-null  object
 4   rate                         41233 non-null  float64
 5   votes                        51099 non-null  int64
 6   location                     51099 non-null  object
 7   rest_type                    51099 non-null  object
 8   dish_liked                   23423 non-null  object
 9   cuisines                     51099 non-null  object
 10  approx_cost(for two people)  51099 non-null  int64
 11  reviews_list                 51099 non-null  object
 12  listed_in(type)              51099 non-null  object
 13  listed_in(city)              51099 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 5.8+ MB

#### Checking for empty values , or characters

In [149]:
df.isin(['',' ', "", " "]).sum()

address                        0
name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
reviews_list                   0
listed_in(type)                0
listed_in(city)                0
dtype: int64

In [150]:
df[df['rest_type'].str.fullmatch(r'[^A-Za-z0-9]+', na=False)]
# r'[^A-Za-z0-9]' = any character that is not a letter or number. and + means one or more like ###,//, $$ etc

Empty DataFrame
Columns: [address, name, online_order, book_table, rate, votes, location, rest_type, dish_liked, cuisines, approx_cost(for two people), reviews_list, listed_in(type), listed_in(city)]
Index: []

#### Mapping Yes and No to 1 and 0

In [156]:
df['online_order'] = df['online_order'].map({'Yes': 1, 'No': 0})
df['book_table'] = df['book_table'].map({'Yes': 1, 'No': 0})

df[['online_order', 'book_table']].head()

   online_order  book_table
0             1           1
1             1           0
2             1           0
3             0           0
4             0           0

In [158]:
(df['online_order'] == 1).sum()

np.int64(30270)

In [160]:
df.to_csv('cleaned_restuarants.csv', index = False)